package it.fivano.damusic.backend.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import it.fivano.damusic.backend.model.UserGenrePreference;
import it.fivano.damusic.backend.model.UserGenrePreferenceExample;
import it.fivano.damusic.backend.model.UserGenrePreferenceKey;

public interface UserGenrePreferenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int countByExample(UserGenrePreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int deleteByExample(UserGenrePreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int deleteByPrimaryKey(UserGenrePreferenceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int insert(UserGenrePreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int insertSelective(UserGenrePreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    List<UserGenrePreference> selectByExample(UserGenrePreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    UserGenrePreference selectByPrimaryKey(UserGenrePreferenceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int updateByExampleSelective(@Param("record") UserGenrePreference record, @Param("example") UserGenrePreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int updateByExample(@Param("record") UserGenrePreference record, @Param("example") UserGenrePreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int updateByPrimaryKeySelective(UserGenrePreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_genre_preference
     *
     * @mbggenerated Sun Sep 01 01:31:17 CEST 2013
     */
    int updateByPrimaryKey(UserGenrePreference record);
}